### ISSUE TITLE
having trouble installing it on my Pi anyone had a similar problem?

### ISSUE THREAD

**Issue by joekeo** [Galarzaa90/NabBot#17]
Hello, I had installed this bot in the past, and wanted to install it again on a new RBPi3.
after writing the bot token and rying to run the bot, I get this error:
```

python3 nabbot.py 
Checking database version...
Version 10
Database is up to date.
Attempting login...
Traceback (most recent call last):
  File "nabbot.py", line 1751, in <module>
    bot.run(token)
  File "/usr/local/lib/python3.4/dist-packages/discord/client.py", line 519, in run
    self.loop.run_until_complete(self.start(*args, **kwargs))
  File "/usr/lib/python3.4/asyncio/base_events.py", line 276, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 233, in _step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.4/dist-packages/discord/client.py", line 491, in start
    yield from self.connect()
  File "/usr/local/lib/python3.4/dist-packages/discord/client.py", line 444, in connect
    self.ws = yield from DiscordWebSocket.from_client(self)
  File "/usr/local/lib/python3.4/dist-packages/discord/gateway.py", line 175, in from_client
    ws = yield from websockets.connect(gateway, loop=client.loop, klass=cls)
  File "/usr/local/lib/python3.4/dist-packages/websockets/client.py", line 160, in connect
    factory, wsuri.host, wsuri.port, **kwds)
  File "/usr/lib/python3.4/asyncio/base_events.py", line 588, in create_connection
    sock, protocol_factory, ssl, server_hostname)
  File "/usr/lib/python3.4/asyncio/base_events.py", line 610, in _create_connection_transport
    yield from waiter
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/selector_events.py", line 727, in _on_handshake
    self._sock.do_handshake()
  File "/usr/lib/python3.4/ssl.py", line 804, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nabbot.py", line 1763, in <module>
    bot.session.close()
  File "/usr/local/lib/python3.4/dist-packages/discord/client.py", line 296, in __getattr__
    raise AttributeError(msg.format(self.__class__, name))
AttributeError: '<class 'discord.ext.commands.bot.Bot'>' object has no attribute 'session'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x75d4f2d0>

```
Any pointers on how to solve it? tried to install an SSL certificate, but my understanding of the topic is too small. ANy help is welcomed :)

**Comment by Galarzaa90** [comment]
I tried looking up your problem and found nothing but "install ssl certificates" and similar solutions.

I run NabBot on a Raspberry Pi too and I never had this problem. I've done it on multiple installs, multiple python installs and never encountered that problem.

I'm closing this issue as is not an issue directly related with NabBot.
