### ISSUE TITLE
makedb.py needs updating

### ISSUE THREAD

**Issue by aveso** [Galarzaa90/NabBot#5]
C:\Users\Luke\Desktop\NabBot>nabbot.py
Logged in as
NabBot
182466599121453056
------
2016-05-18 16:10:40,056:INFO: Bot is online and ready
Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\discord\client.py", line 244, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\Users\Luke\Desktop\NabBot\nabbot.py", line 28, in on_ready
    yield from think()
  File "C:\Users\Luke\Desktop\NabBot\nabbot.py", line 102, in think
    c.execute("SELECT name, last_level, id FROM chars WHERE name LIKE ?",(serverChar['name'],))
sqlite3.OperationalError: no such table: chars

As the title says, with the new version I'm pretty sure either makedb.py needs an update or the database.py does.

**Comment by Galarzaa90** [comment]
I just updated makedb.py in commit 64f122c23202a8f019df4e054151ed98679e0176

I'm planning on removing makedb.py and instead checking if the users database exists (and is updated) on startup.

Thanks
