### ISSUE TITLE
TypeError: '<=' not supported between instances of 'int' and 'NoneType'

### ISSUE THREAD

**Issue by drptbl** [Galarzaa90/NabBot#87]
```
Traceback (most recent call last):
  File "nabbot.py", line 440, in <module>
    nabbot.run(token)
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 580, in run
    return task.result()
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 488, in start
    yield from self.connect(reconnect=reconnect)
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 408, in connect
    yield from self._connect()
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 370, in _connect
    yield from self.ws.poll_event()
  File "/usr/local/lib/python3.6/dist-packages/discord/gateway.py", line 448, in poll_event
    msg = yield from self.recv()
  File "/usr/local/lib/python3.6/dist-packages/websockets/protocol.py", line 323, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
  File "/usr/local/lib/python3.6/dist-packages/websockets/exceptions.py", line 147, in __init__
    if 3000 <= code < 4000:
TypeError: '<=' not supported between instances of 'int' and 'NoneType'
```

I'm not sure why and when it happened (NabBot is running on VPS), but I'm guessing that it lost connection with Discord and tried to reconnect - then it crashed.

**Comment by Galarzaa90** [comment]
What version of discord.py are you using?

This seems like an issue with discord.py.

If you know how to run python on the command line:
```cmd
>python
Python 3.6.x
>>> import discord
>>> discord.version
'1.0.0a'
```

Example:
![image](https://user-images.githubusercontent.com/12865379/38529617-c4931282-3c1a-11e8-849f-b61ebe0b7514.png)

**Comment by drptbl** [comment]
@Galarzaa90 Sorry for not providing these details at the beginning, please let me know if you more.
![discord_version](https://user-images.githubusercontent.com/8177587/38544525-f6dd03e6-3ca7-11e8-82b8-c0a34a4598bf.PNG)

**Comment by Galarzaa90** [comment]
I wasn't able to reproduce this, exactly how are you running NabBot?

**Comment by drptbl** [comment]
@Galarzaa90 Sorry but I'm not using NabBot actively anymore, so it seems that we can close this one.
